# build_libressl(BINARY SUFFIX PIC)
#
# Downloads and builds LibreSSL as static libraries (libssl, libcrypto) into
# ${BINARY}/deps-${SUFFIX}. Sets LIBRESSL_INCLUDE_DIR_${SUFFIX},
# LIBRESSL_LIBRARY_DIR_${SUFFIX} and LIBRESSL_LIBRARIES_${SUFFIX} (full paths of
# ssl, crypto); the ExternalProject target is libressl_${SUFFIX}.
macro(build_libressl BINARY SUFFIX PIC)
  include(ExternalProject)

  message("-- Building LibreSSL from source (${SUFFIX}, PIC=${PIC})")

  set(LIBRESSL_VERSION 4.0.0)
  set(LIBRESSL_PREFIX_${SUFFIX} "${BINARY}/deps-${SUFFIX}")
  set(LIBRESSL_INCLUDE_DIR_${SUFFIX} "${LIBRESSL_PREFIX_${SUFFIX}}/include")
  set(LIBRESSL_LIBRARY_DIR_${SUFFIX} "${LIBRESSL_PREFIX_${SUFFIX}}/lib")
  set(LIBRESSL_LIBRARIES_${SUFFIX}
      "${LIBRESSL_LIBRARY_DIR_${SUFFIX}}/${CMAKE_STATIC_LIBRARY_PREFIX}ssl${CMAKE_STATIC_LIBRARY_SUFFIX}"
      "${LIBRESSL_LIBRARY_DIR_${SUFFIX}}/${CMAKE_STATIC_LIBRARY_PREFIX}crypto${CMAKE_STATIC_LIBRARY_SUFFIX}")

  ExternalProject_Add(
    libressl_${SUFFIX}
    URL https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${LIBRESSL_VERSION}.tar.gz
    DOWNLOAD_DIR ${BINARY}/downloads-${SUFFIX}
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    BINARY_DIR ${BINARY}/libressl-${SUFFIX}
    CMAKE_CACHE_ARGS
      "-DCMAKE_INSTALL_PREFIX:PATH=${LIBRESSL_PREFIX_${SUFFIX}}"
      "-DCMAKE_INSTALL_LIBDIR:PATH=lib"
      "-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}"
      "-DCMAKE_SYSROOT:PATH=${CMAKE_SYSROOT}"
      "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}"
      "-DCMAKE_C_FLAGS:STRING=-w"
      "-DCMAKE_VERBOSE_MAKEFILE:BOOL=${CMAKE_VERBOSE_MAKEFILE}"
      "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
      "-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=${PIC}"
      "-DBUILD_SHARED_LIBS:BOOL=OFF"
      "-DLIBRESSL_APPS:BOOL=OFF"
      "-DLIBRESSL_TESTS:BOOL=OFF"
    BUILD_BYPRODUCTS ${LIBRESSL_LIBRARIES_${SUFFIX}})
endmacro()
