function(find_system_prefix)
  if(ARGN)
    set(VARS ${ARGN})
  else(ARGN)
    set(VARS SHELL BASH)
  endif(ARGN)
  foreach(VAR ${VARS})
    string(REGEX REPLACE ".*/" "" PROGRAM_SHELL $ENV{${VAR}})
    find_program("${VAR}" "${PROGRAM_SHELL}")

    if(EXISTS "${${VAR}}")
       string(REGEX REPLACE "\/bin\/.*$" "" SYSTEM_PREFIX "${${VAR}}")
       break()
    endif(EXISTS "${${VAR}}")
  endforeach(VAR ${VARS})
  
  set(SYSTEM_PREFIX "${SYSTEM_PREFIX}" PARENT_SCOPE)
endfunction(find_system_prefix)

function(find_resolv_conf)
  foreach(PATH ${ARGN})
    if(EXISTS "${PATH}")
      set(RESOLV_CONF "${PATH}" CACHE FILEPATH "Location of resolv.conf")
      break()
    endif(EXISTS "${${VAR}}")
  endforeach(PATH ${ARGN})
  
  set(RESOLV_CONF "${RESOLV_CONF}" PARENT_SCOPE)
endfunction(find_resolv_conf)
